import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Dock from "@/components/Dock";
import MenuBar from "@/components/MenuBar";
import ApplicationHolder from "@/components/ApplicationHolder";
import Finder from "@/components/Finder";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="relative" id="home">
          <MenuBar/>
          <ApplicationHolder active>
            {true&&<Finder>

        {children}
            </Finder>}
      </ApplicationHolder>  
            <Dock/>
        </div>
      </body>
    </html>
  );
}
